"use client";

// import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "../../styles/style.css";
import { useEffect } from "react";
import { SessionProvider } from "next-auth/react";
import { MyProvider } from "../components/context";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <MyProvider>{children}</MyProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
