"use client";

// import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "../../styles/style.css";
import { useEffect, useState } from "react";
import { SessionProvider } from "next-auth/react";
import { MyProvider } from "../components/context";

import { Alert, Box, Container, Typography } from "@mui/material";
import BackdropComponent from "../components/UI-component/backdrop";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);

  const [backDropOpen, setBackDropOpen] = useState(true);
  const [isMobile, setIsMobile] = useState("loading");
  const checkIfMobile = () => {
    const userAgent =
      typeof window !== "undefined" ? navigator.userAgent.toLowerCase() : "";
    const screenWidth = typeof window !== "undefined" ? window.innerWidth : 0;

    // Check user agent and screen width
    const mobileUserAgent = userAgent.match(/android|iphone|ipad|ipod/i);
    const mobileScreenWidth = screenWidth < 768; // Adjust as necessary

    return mobileUserAgent || mobileScreenWidth;
  };

  useEffect(() => {
    const handleResize = () => {
      const mobile = checkIfMobile();
      setIsMobile(mobile);
    };

    setBackDropOpen(true);
    handleResize();
    setBackDropOpen(false);

    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    <html lang="en">
      <body>
        {isMobile === "loading" ? (
          <BackdropComponent open={backDropOpen} setOpen={setBackDropOpen} />
        ) : isMobile ? (
          <Container>
            <Box
              display="flex"
              flexDirection="column"
              alignItems="center"
              justifyContent="center"
              height="100vh"
              textAlign="center"
            >
              <Typography variant="h4" gutterBottom>
                Mobile Access Not Supported
              </Typography>
              <Typography variant="body1">
                We apologize, but our application is currently not supported on
                mobile devices. For the best experience, please access our
                website using a desktop or laptop computer.
              </Typography>
            </Box>
          </Container>
        ) : (
          <SessionProvider>
            <MyProvider>{children}</MyProvider>
          </SessionProvider>
        )}
      </body>
    </html>
  );
}
